### ISSUE TITLE
PANIC: illegal Pos value with github.com/gonum/matrix/mat64

### ISSUE THREAD

**Issue by kortschak** [cznic/browse#3]
Attempting to browse gonum/matrix/mat64 does the following:

```
$ browse github.com/gonum/matrix/mat64
main.go:158: goroutine 52 [running]:
runtime/debug.Stack(0xc420043940, 0x5c00a0, 0xc420cfba40)
	/home/daniel/go/src/runtime/debug/stack.go:24 +0x79
github.com/cznic/browse/internal/gc.(*Context).load.func1.1(0xc420014f60)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:333 +0x6e
panic(0x5c00a0, 0xc420cfba40)
	/home/daniel/go/src/runtime/panic.go:489 +0x2cf
github.com/cznic/browse/internal/ftoken.(*File).PositionFor(0xc420e00f60, 0x163e5c, 0x40b201, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/ftoken/position.go:222 +0x110
github.com/cznic/browse/internal/ftoken.(*File).Position(0xc420e00f60, 0x163e5c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/ftoken/position.go:233 +0x7d
github.com/cznic/browse/internal/gc.(*Bindings).declare(0xc4209be100, 0xc4202ebea0, 0x6d5c00, 0xc420d79760)
	/home/daniel/src/github.com/cznic/browse/internal/gc/decl.go:45 +0x1d1
github.com/cznic/browse/internal/gc.(*Scope).declare(0xc4209be100, 0xc4202ebea0, 0x6d5c00, 0xc420d79760)
	/home/daniel/src/github.com/cznic/browse/internal/gc/decl.go:110 +0x1dd
github.com/cznic/browse/internal/gc.(*parser).topLevelDeclList(0xc4202ebea0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/parser.go:1629 +0x3d7
github.com/cznic/browse/internal/gc.(*parser).file(0xc4202ebea0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/parser.go:1699 +0x165
github.com/cznic/browse/internal/gc.(*Package).load(0xc4200f0750, 0xc42027d740, 0x36, 0xec, 0xc, 0x2, 0xc4200fae00, 0x13, 0x20, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:510 +0x3aa
github.com/cznic/browse/internal/gc.(*Context).load.func1(0xc420014f60, 0xc420080100, 0xc4208eb4a1, 0x1d, 0xc4200f0750, 0xc42027d740, 0x36, 0xec, 0xc, 0x2, ...)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:345 +0x140
created by github.com/cznic/browse/internal/gc.(*Context).load
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:346 +0x408

PANIC: illegal Pos value
goroutine 65 [running]:
runtime/debug.Stack(0xc42046f940, 0x5c00a0, 0xc420ff2ea0)
	/home/daniel/go/src/runtime/debug/stack.go:24 +0x79
github.com/cznic/browse/internal/gc.(*Context).load.func1.1(0xc420014f60)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:333 +0x6e
panic(0x5c00a0, 0xc420ff2ea0)
	/home/daniel/go/src/runtime/panic.go:489 +0x2cf
github.com/cznic/browse/internal/ftoken.(*File).PositionFor(0xc420e1b5c0, 0x2c2a58, 0x40b201, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/ftoken/position.go:222 +0x110
github.com/cznic/browse/internal/ftoken.(*File).Position(0xc420e1b5c0, 0x2c2a58, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/ftoken/position.go:233 +0x7d
github.com/cznic/browse/internal/gc.(*Bindings).declare(0xc421298ec0, 0xc420b2df90, 0x6d5c00, 0xc420cf02a0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/decl.go:45 +0x1d1
github.com/cznic/browse/internal/gc.(*Scope).declare(0xc421298ec0, 0xc420b2df90, 0x6d5c00, 0xc420cf02a0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/decl.go:110 +0x1dd
github.com/cznic/browse/internal/gc.(*parser).topLevelDeclList(0xc420b2df90)
	/home/daniel/src/github.com/cznic/browse/internal/gc/parser.go:1629 +0x3d7
github.com/cznic/browse/internal/gc.(*parser).file(0xc420b2df90)
	/home/daniel/src/github.com/cznic/browse/internal/gc/parser.go:1699 +0x165
github.com/cznic/browse/internal/gc.(*Package).load(0xc4206a6000, 0xc42027d900, 0x3f, 0x108, 0xc, 0x7, 0xc4212cbc80, 0x3, 0x4, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:510 +0x3aa
github.com/cznic/browse/internal/gc.(*Context).load.func1(0xc420014f60, 0xc420080100, 0xc420da88d1, 0x2c, 0xc4206a6000, 0xc42027d900, 0x3f, 0x108, 0xc, 0x7, ...)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:345 +0x140
created by github.com/cznic/browse/internal/gc.(*Context).load
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:346 +0x408

PANIC: illegal Pos value
goroutine 7 [running]:
runtime/debug.Stack(0xc420069940, 0x5c00a0, 0xc421163810)
	/home/daniel/go/src/runtime/debug/stack.go:24 +0x79
github.com/cznic/browse/internal/gc.(*Context).load.func1.1(0xc420014f60)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:333 +0x6e
panic(0x5c00a0, 0xc421163810)
	/home/daniel/go/src/runtime/panic.go:489 +0x2cf
github.com/cznic/browse/internal/ftoken.(*File).PositionFor(0xc421ed8a20, 0x393aac, 0x40b201, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/ftoken/position.go:222 +0x110
github.com/cznic/browse/internal/ftoken.(*File).Position(0xc421ed8a20, 0x393aac, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/ftoken/position.go:233 +0x7d
github.com/cznic/browse/internal/gc.(*Bindings).declare(0xc420013800, 0xc420016d20, 0x6d5c00, 0xc421495380)
	/home/daniel/src/github.com/cznic/browse/internal/gc/decl.go:45 +0x1d1
github.com/cznic/browse/internal/gc.(*Scope).declare(0xc420013800, 0xc420016d20, 0x6d5c00, 0xc421495380)
	/home/daniel/src/github.com/cznic/browse/internal/gc/decl.go:110 +0x1dd
github.com/cznic/browse/internal/gc.(*parser).topLevelDeclList(0xc420016d20)
	/home/daniel/src/github.com/cznic/browse/internal/gc/parser.go:1629 +0x3d7
github.com/cznic/browse/internal/gc.(*parser).file(0xc420016d20)
	/home/daniel/src/github.com/cznic/browse/internal/gc/parser.go:1699 +0x165
github.com/cznic/browse/internal/gc.(*Package).load(0xc4200f0090, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200fa600, 0x18, 0x20, 0x0)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:510 +0x3aa
github.com/cznic/browse/internal/gc.(*Context).load.func1(0xc420014f60, 0xc420080100, 0x7ffdac3a2173, 0x1d, 0xc4200f0090, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:345 +0x140
created by github.com/cznic/browse/internal/gc.(*Context).load
	/home/daniel/src/github.com/cznic/browse/internal/gc/context.go:346 +0x408

PANIC: illegal Pos value
```

**Comment by cznic** [comment]
@kortschak Thank you for the report! Please test and reopen if it still does not work for you, thanks.

**Comment by kortschak** [comment]
Thank you, that fixes it.
